### ISSUE TITLE
Why was BIP39 not utilized for seed instead of ad-hoc dictionary

### ISSUE THREAD

**Issue by D-Nice** [SkynetLabs/skynet-mysky#103]
The only reason I could see is that under no circumstances would you want someone entering a mnemonic that may actually hold cryptocurrency, however, there already exists a whole ecosystem for storing BIP39 mnemonics and it's quite battle tested.

**Comment by m-cat** [comment]
From what I remember, we felt that we could do better than BIP39 and we optimised it for browsers. For example, we use a shorter dictionary that takes up less memory (we also use shorter words to make the phrase a bit more user-friendly).

Closing as this is not an "issue" but feel free to start a "discussion" if you wish.
