### ISSUE TITLE
Only prompt for permissions if user seed is already saved.

### ISSUE THREAD

**Issue by dghelm** [SkynetLabs/skynet-mysky#81]
## Describe the bug
Right now, if I am logged into MySky and visit a page where I need to approve permissions, clicking the "authenticate with MySky" button requires me to input my seed instead of directly prompting the permissions page.

## Expected behavior
I'm logged into homescreen.hns.siasky.net, I open a v1 skylink to rift, I click "Login," I am not asked for a seed phrase, but instead asked about permissions.

**Comment by m-cat** [comment]
This has been fixed, closing.
